### ISSUE TITLE
Scheduled jobs ?

### ISSUE THREAD

**Issue by Sephi-Chan** [bkeepers/qu#11]
Hello,

I would like to know if job scheduling was in the todo list.
It's a feature I often need as a webgame developer! :)

Thanks and good luck!

**Comment by bkeepers** [comment]
Hi @Sephi-Chan,

Thanks for your interest in qu. In the future, would you posting questions on the mailing list? I'm going to try to keep the Issues to know bugs and planned features.

I don't have a need for scheduling, but I'm not opposed to working with someone to implement it.

**Comment by Sephi-Chan** [comment]
Ok, for the mailing list. ;) I never contributed to an open source project before.
This feature is a bit difficult due to the multiple backends and capabilities to react at time, but I would be glad to help. What can I do?
