### ISSUE TITLE
Invalid use of `retry`

### ISSUE THREAD

**Issue by mindscratch** [bkeepers/qu#12]
When I run qu-mongo with ruby 1.9.2p290, it appears the use of [retry](https://github.com/bkeepers/qu/blob/master/lib/qu/backend/mongo.rb#L63) is invalid.

Specifically the error from ruby is just "Invalid retry".

It seems as though the context in which you are using `retry` would have worked in Ruby 1.8 but no longer does in 1.9. I believe the idea of `retry` is to do something again if an exception occurs.

reference: http://www.ruby-forum.com/topic/184694

**Comment by mindscratch** [comment]
Actually, I was going to attempt to fix this issue, but first I'd like to know, what was your intention when using "retry"? What were you expecting to happen when retry was invoked?

**Comment by bkeepers** [comment]
@mindscratch thanks for reporting the issue. I didn't realize they changed the behavior of retry between Ruby 1.8 and 1.9.

The goal is to make #reserve block until it is able to return a job. I suppose the proper way to do it would be to replace the retry with a loop and break out of it when a job is found.

Also, if you're using MongoDB 2.0, be aware of #10.

**Comment by mindscratch** [comment]
@bkeepers: I did see issue #10 and I am planning on using Mongo 2.0 :)

I agree a loop seems to make the most sense, what do you think about having the options hash have another potential option such as "max_retries" => 3....meaning, retry up to 3 times. If no job is found after the max_retries raise the Mongo::OperationFailure.  This would mean that the redis and mongo backends would vary slightly b/c the redis backend wouldn't have a use for "max_retries" (that I know of unless the redis api accepts that sort of param when doing a blpop operation). But it might be ok for the variation since it's just "options".

Let me know what you think.

**Comment by mindscratch** [comment]
When I run: rake spec or rake spec:mongo ..I get the following error:

``` bash
code/projects/qu[master]% rake spec
There are no gemspecs at /Users/craig/code/projects/qu.
rake aborted!
ruby -S bundle exec rspec --color ./spec/qu/backend/mongo_spec.rb ./spec/qu/backend/redis_spec.rb ./spec/qu/failure/exceptional_spec.rb ./spec/qu/job_spec.rb ./spec/qu/worker_spec.rb ./spec/qu_spec.rb failed

Tasks: TOP => spec
```

Any ideas?

**Comment by bkeepers** [comment]
Make sure you pull the latest. Should be all fixed as of yesterday

**Comment by mindscratch** [comment]
Got it thanks. Also, thanks for the "retry" fix...I was working on my own fix today but when I did the rebase I saw you fixed it :)
