### ISSUE TITLE
exception in unregister_worker

### ISSUE THREAD

**Issue by gregory-m** [bkeepers/qu#13]
Hi.

unregister_worker method in Backend classes assume to get id as parameter, but Worker class in start method (line 61) pass worker object to it. 

And because of this we get exception:

```
Cannot serialize an object of class Qu::Worker into BSON.
/Users/gregory/.rvm/gems/ree-1.8.7-2011.03@applicaster-encoder/gems/bson-1.4.0/lib/../lib/bson/bson_c.rb:24:in `serialize'
/Users/gregory/.rvm/gems/ree-1.8.7-2011.03@applicaster-encoder/gems/bson-1.4.0/lib/../lib/bson/bson_c.rb:24:in `serialize'
/Users/gregory/.rvm/gems/ree-1.8.7-2011.03@applicaster-encoder/gems/mongo-1.3.1/lib/../lib/mongo/collection.rb:344:in `remove'
/Users/gregory/.rvm/gems/ree-1.8.7-2011.03@applicaster-encoder/gems/qu-mongo-0.1.0/lib/qu/backend/mongo.rb:87:in `unregister_worker'
/Users/gregory/.rvm/gems/ree-1.8.7-2011.03@applicaster-encoder/gems/qu-0.1.0/lib/qu/worker.rb:49:in `start'
.....
```

And though the specs are passed, qu raise exception in real projects. Maybe you need any kind of integration tests?

Thanks.

**Comment by bkeepers** [comment]
Thanks for the report. Crazy that I haven't run across this in production yet. I was definitely thinking some integration tests were in order.

I'll get it fixed today.
