### ISSUE TITLE
logger variable does not exist when running outside of Rails

### ISSUE THREAD

**Issue by mindscratch** [bkeepers/qu#15]
The "logger" variable that's used in Qu (such as mongo.rb) is not available when Qu is not running in a Rails application.

**Comment by bkeepers** [comment]
Are you sure? It should be getting set to a default logger. https://github.com/bkeepers/qu/blob/master/lib/qu.rb#L34 

Are you getting an error?

**Comment by mindscratch** [comment]
@bkeepers - you're certainly right. I'd have to dig through the commit history but I must have grabbed a copy of master where the logger was being used (in mongo.db specifically) but wasn't being setup like it currently is in qu.rb.

The code I'm looking at does not have the...

``` ruby
Qu.configure do |c|
  c.logger = Logger.new(STDOUT)
  c.logger.level = Logger::INFO
end
```

that qu.rb has now.

**Comment by bkeepers** [comment]
@mindscratch ah, yeah, there may have been a few commits between when the logger was added and the default configuration was added.
