### ISSUE TITLE
Error when enqueueing a job: Database names cannot contain the character '.'

### ISSUE THREAD

**Issue by mindscratch** [bkeepers/qu#19]
I'm using the following versions of things:
- rails 3.1
- ruby 1.9.2 p290
- mongoid 2.2.1
- qu 0.1.1
- mongo 1.4.0
- bson_ext 1.4.0
- MongoDB 2.0.0

I am configuring Qu's connection to MongoDB with this bit of code defined in a Rails initializer:

``` ruby
Qu.configure do |c|
    uri = 'mongodb://username:password@localhost:50000/qu_dev'
    c.connection = Mongo::Connection.from_uri uri
end
```

When I try to enqueue a job I'm getting the following error:

```
database names cannot contain the character '.'
<gems_path>/mongo-1.4.0/lib/mongo/util/support.rb:54:in `block in validate_db_name'
<gems_path>/mongo-1.4.0/lib/mongo/util/support.rb:52: `each'
<gems_path>/mongo-1.4.0/lib/mongo/util/support.rb:52: `validate_db_name'
<gems_path>/mongo-1.4.0/lib/mongo/db.rb:80:in `initialize'
<gems_path>/mongo-1.4.0/lib/mongo/connectino.rb:312:in `new'
<gems_path>/mongo-1.4.0/lib/mongo/connectino.rb:312:in `[]'
<gems_path>/qu-mongo-0.1.1/lib/qu/backend/mongo.rb:122:in `[]'
<gems_path>/qu-mongo-0.1.1/lib/qu/backend/mongo.rb:118:in `jobs'
<gems_path>/qu-mongo-0.1.1/lib/qu/backend/mongo.rb:42:in `enqueue' 
<gems_path>/qu-0.1.1/lib/qu.rb:29:in `enqueue'
```

The name of my job was "tasks":

``` ruby
class TaskJob
  @queue = :tasks

   self.perform
   end
```

This problem also occurred when using the Mongo Ruby driver v1.3.1. 

Looking at the code it appears that qu/backend/mongo.rb#[ ] method is trying to get a reference to a collection but it's using the [Mongo::Connection#[ ]](http://api.mongodb.org/ruby/current/Mongo/Connection.html#[]-instance_method) method to do it, which actually gives back a Mongo::DB instance. (the API for version 1.3.1 of the Mongo Ruby driver also behaves the same way as 1.4.0).

I suppose I'm doing something wrong since enqueueing is so fundamental to Qu :)

**Comment by mindscratch** [comment]
The actualy "name" being [passed](https://github.com/bkeepers/qu/blob/v0.1.1/lib/qu/backend/mongo.rb#L122) to the Mongo::Connection[ ] is "qu.queue:tasks".

On a side note, that may be a bug. It appears that it's trying to access the "qu" database however my database name is "qu_dev".

**Comment by mindscratch** [comment]
doh! I screwed up my configuration of the Qu.connection. I should have done:

``` ruby
Qu.configure do |c|
    uri = 'mongodb://username:password@localhost:50000/qu_dev'
    c.connection = Mongo::Connection.from_uri(uri).db('qu_dev')
end
```

**Comment by bkeepers** [comment]
Cool. Let me know if you run into any other issues.
