### ISSUE TITLE
Add hooks

### ISSUE THREAD

**Issue by bkeepers** [bkeepers/qu#2]
:enqueue
:before
:after
:failure
:complete
:requeue
:release

**Comment by mindscratch** [comment]
Brandon -- I realize you've probably been busy with other stuff, but I was curious where you were at with the hooks API implementation. Things have been a bit quiet the last couple of weeks.

**Comment by bkeepers** [comment]
@mindscratch yeah, sorry, I've had a few too many irons in the fire.  The work on hooks is mostly done in the [hooks branch](https://github.com/bkeepers/qu/tree/hooks). Give it a try and let me know how it works for you.

The main reason I haven't it merged it into master and released it is that I haven't had a chance to update my project to use it. I want to make sure I like using it before committing to the API.

**Comment by didip** [comment]
This is exactly what I need at work. We have a background job connecting to external service that's very finicky.

I'd like to be able to send email to customer service department when job failed and have them handle it manually.

Qu is looking better and better. Thanks for creating it!

**Comment by jnunemaker** [comment]
Merged support for before/after for each of these events: :enqueue, :perform, :complete, :release, :failure.
