### ISSUE TITLE
Redis jobs not being cleaned out properly

### ISSUE THREAD

**Issue by fbjork** [bkeepers/qu#21]
Hi,

I'm using the latest version of Qu. When I check each queue length it says zero. However when I list keys \* in Redis I get this: https://gist.github.com/6ed74e94daccf4cfa0ff

Any ideas?

This is on Heroku.

**Comment by bkeepers** [comment]
Do you have any failed jobs? `Qu.length('failed')`

Qu _should_ clear out the jobs that are completed: https://github.com/bkeepers/qu/blob/master/lib/qu/backend/redis.rb#L67-69

**Comment by fbjork** [comment]
Ah there you go. Lots of failed jobs. Anyway of inspecting failed jobs without going into redis-cli?

**Comment by fbjork** [comment]
What determines if a job failed?

**Comment by fbjork** [comment]
When I did: Qu.clear(:failed), Qu.length(:failed) returns 0, but keys \* in redis-cli still shows thousands of qu keys. Ideas? Looks like jobs aren't being removed from Redis properly?

**Comment by bkeepers** [comment]
Failed jobs are ones that raised an exception. There isn't currently a way to inspect the errors through qu. I've been using qu-exceptional to report them to http://getexceptional.com, so I haven't had the need for other ways of inspecting the errors.

Also, clearing the queue apparently doesn't delete the jobs from redis.  That's an oversight on my part. I'll get that fixed.
