### ISSUE TITLE
Duplicate collections

### ISSUE THREAD

**Issue by fbjork** [bkeepers/qu#26]
Not sure if this is qu related or not, but I thought I'd share it in case. I just updated to the latest version of qu-mongo and deployed to Heroku. All of a sudden all the qu collections are duplicate!

These are the collections in my qu database:
qu.workers
qu.queue:sync_friends
qu.queues
qu.queue:sync_account
qu.workers
qu.queue:sync_friends
qu.queues
qu.queue:sync_account

Any ideas?

**Comment by bkeepers** [comment]
Odd, I have no clue. I don't think anything has changed with the collections in qu
