### ISSUE TITLE
Retry logic

### ISSUE THREAD

**Issue by fbjork** [bkeepers/qu#30]
How is the retry logic meant to work in qu? If an exception is raised, will the the worker retry the job (5 times be default in mongo) and if it fails write it to the failed collection?

**Comment by bkeepers** [comment]
There currently isn't retry logic. If an exception is raised, the job is added to the "failed" queue and it goes on to the next job. Qu doesn't currently offer a lot of visibility into the errors, so I'd recommend using the qu-exceptional backend (or write qu-airbrake) to report the errors to a separate service.

Once hooks are implemented, I'll add a retry plugin that lets you specify which errors should be retried and how many times.
