### ISSUE TITLE
Question: How can I set a task to be performed only when it reaches an specific date?

### ISSUE THREAD

**Issue by Nerian** [bkeepers/qu#37]
I want to create a Task, that contains the day it which it was created. When the task is, say, 12h old it should perform its task.

What could be an elegant way to do this?

**Comment by bkeepers** [comment]
You can't at this time. I'd recommend checking out rescue-scheduler or delayed_job for now. Qu may add support for scheduling at some point, but it's not high on the priorities right now.

**Comment by Nerian** [comment]
ok, thanks :)
