### ISSUE TITLE
Get Notified By Job Successfully Complete

### ISSUE THREAD

**Issue by shenoudab** [bkeepers/qu#50]
Dears, 

```
kindly, is there a way to get notified when the Job Done Successfully Completed.
also, how can use qu to add a progress bar to the form for a Job.
something like speakerdeck.com presentation Uploader Processing Progress.
```

Best Regards,
Shenouda Bertel

**Comment by bkeepers** [comment]
On SpeakerDeck, we manage this state in the model. As slides are processed, we mark them as such in the database and then display that state in the UI.

There is nothing in Qu like this right now, and I'm not sure if there ever will be.
