### ISSUE TITLE
[HireFire] Extract a "working" worker's job's queue name

### ISSUE THREAD

**Issue by mrrooijen** [bkeepers/qu#53]
Hey guys,

I am currently in the process of finishing up a full rewrite of the [HireFire](http://hirefireapp.com/) system, and I am currently trying to add support for the Qu worker library as well as it's been requested by a bunch of HireFire users.

Thus far it seems to be working pretty well, but I am still missing something, namely the ability to see which `job` a `worker` is currently processing (if any). Is it possible to extract that data with the current code base?

Here is an implementation for counting queues in Resque and Qu for the new HireFire client gem.

https://gist.github.com/15962d22d41562e03323

Notice how I commented out two parts in the Qu macro. These are the things I am unsure of how to do. However, it might not even be necessary but I'd like to confirm this with you.

The scenario is as follows; When you pop a job from the queue in for example Redis, and immediately call `Qu.backend.length`, will it return `0` or `1`? And if it returns `0` could that mean the `worker` is still actually processing the job or has the worker definitely finished processing the job? (Assuming there was only 1 job in the queue before pop-ing).

Also, does this result differ from the Mongo backend?

HireFire is basically an autoscaler for web and worker dynos on Heroku. Now, it might be a problem if a worker is still processing a job, but Qu is reporting `0` so HireFire will think it's clear to spin down all workers, potentially causing the worker to be interrupted and fails the job. Resque provides a method to return all the workers that are currently "working", and they contain the job object and their data (such as the name of the queue the job was pushed in to). Using that information I am capable of doing a `total_queue_size + total_workers_working` to ensure that when `0` is returned, it means there is definitely nothing in the queue, and there is nothing being processed from the queue by any worker.

Any help/tips/feedback much appreciated!

Cheers,
Michael

**Comment by bkeepers** [comment]
> HireFire is basically an autoscaler for web and worker dynos on Heroku.

Yeah, I love HireFire. I've been wanting to make it work with speakerdeck.com.

> The scenario is as follows; When you pop a job from the queue in for example Redis, and immediately call `Qu.backend.length`, will it return `0` or `1`?

`0`. 

> And if it returns `0` could that mean the worker is still actually processing the job or has the worker definitely finished processing the job?

It could still be processing the job.

> Also, does this result differ from the Mongo backend?

Nope, all qu backends should operate identically.

> Resque provides a method to return all the workers that are currently "working", and they contain the job object and their data (such as the name of the queue the job was pushed in to).

Workers are busy if they have the `working_on` attribute set.

``` ruby
total_workers_working = Qu.backend.workers.select { |w| w.working_on }.size
```

Unfortunately, it doesn't store the job data, so you don't know which queue those workers are working on. I don't have a good reason why, so I would be in favor of having Worker#working_on return all the meta-data about a job.

**Comment by jnunemaker** [comment]
Is this still valid? Let me know if there is still work to do or if we can close this.

**Comment by mrrooijen** [comment]
It's been resolved. I'll close it. :)
