### ISSUE TITLE
Auto Redic/Mongo mount while rake spec

### ISSUE THREAD

**Issue by DeTeam** [bkeepers/qu#61]
It'd be just handy to automatically setup Redis and Mongo server instances while trying to run tests.

**Comment by jnunemaker** [comment]
Thanks for the suggestion. We'll probably not tackle that but if a good pull request came in that did it, we would certainly take a look.

More likely I'll maybe split out the various backends from this repo so you can work on one backend at a time or make some way to do the same thing in only this repo.
