### ISSUE TITLE
Current status of project

### ISSUE THREAD

**Issue by adamlwatson** [bkeepers/qu#67]
Hi there...  I've implemented Qu in a current project and am liking it so far. Looking through the issues here, as well as the Google Group, I get the feeling that this project has stalled in terms of recent updates...  is this the case? The questions I have posted to the group don't appear (as if they aren't being moderated), and I seem pull requests and issues from months and years ago not addresses.

Is Qu being supported any longer, or is there another branch of this that is more active?

Thanks,
Adam

**Comment by bkeepers** [comment]
>  I get the feeling that this project has stalled in terms of recent updates... is this the case?

That is the case. I haven't had time or the need to make changes.

> The questions I have posted to the group don't appear (as if they aren't being moderated)

Weird, I haven't seen any moderation emails come through. I'll check on that.

I'm happy to hand the project over to anyone that is capable and willing.

**Comment by jnunemaker** [comment]
@adamlwatson I am hoping to bring some new life. I like the project and have some ideas.

**Comment by adamlwatson** [comment]
Fantastic to hear, @jnunemaker — I'm using it on a project in production now, and am more that happy to commit back wherever I can...

**Comment by jnunemaker** [comment]
@adamlwatson which backend are you using?

**Comment by adamlwatson** [comment]
@jnunemaker Using mongo, here.

**Comment by bkeepers** [comment]
@jnunemaker I'm really excited that you're taking this over! :metal:
